/**
 * Central website configuration.
 */
export const SITE = {
  name: 'SlipUpClipz',
  tagline: 'Capture what they just said. Replay it instantly.',
  websiteUrl: 'https://slipupclipz.com',
  downloadUrl: '/download/latest',
  releasesUrl: 'https://github.com/FISHSTICKSBOI1/SlipUpClipz/releases/latest',
  currentVersion: '0.1.4',
  installerSizeLabel: '~82.4 MB',
  checkoutEndpoint: '/.netlify/functions/create-checkout',
  validateLicenseEndpoint: '/.netlify/functions/validate-license',
  billingPortalEndpoint: '/.netlify/functions/billing-portal',
  stripeWebhookEndpoint: '/.netlify/functions/stripe-webhook',
  helpCenterUrl: 'https://slipupclipz.com/help',
  contactUrl: 'https://slipupclipz.com/contact',
  supportEmail: 'slipupclipz@gmail.com',
  supportFormName: 'slipupclipz-support',
  supportMailtoSubject: 'SlipUpClipz Support Request',
  supportAssistantEndpoint: '/.netlify/functions/support-assistant',
  demoVideoUrl: 'https://youtu.be/SwqrNqYVWMs?si=z1DpIM1PrfA7mMAv',
  demoVideoEmbedUrl: 'https://www.youtube-nocookie.com/embed/SwqrNqYVWMs',
  vbAudioUrl: 'https://vb-audio.com/Cable/',
  githubRepoUrl: 'https://github.com/FISHSTICKSBOI1/SlipUpClipz',
  logoUrl: '/images/logo.png',
  ogImageUrl: '/images/og-preview.png',
  pricing: {
    freeName: 'Free',
    proName: 'Pro',
    proPriceLabel: '$4.99',
    proPriceInterval: '/year',
    proPriceNote: 'Annual subscription · renews yearly · cancel anytime',
  },
  social: {
    tiktok: '',
    youtube: '',
    youtubeChannelName: 'Slipupclipz',
    discord: 'https://discord.com/invite/c8wX9AUREj',
  },
  paths: {
    home: '/',
    features: '/features',
    howItWorks: '/how-it-works',
    pricing: '/pricing',
    download: '/download',
    help: '/help',
    contact: '/contact',
    faq: '/faq',
    changelog: '/changelog',
    privacy: '/privacy',
    terms: '/terms',
    refund: '/refund',
  },
  screenshots: {
    clips: '/images/screenshots/clips-page.png',
    replay: '/images/screenshots/clips-page.png',
    trim: '/images/screenshots/trim-editor.png',
    soundboard: '/images/screenshots/soundboard.png',
    voiceEffects: '/images/screenshots/voice-effects.png',
    onboarding: '/images/screenshots/onboarding.png',
    settings: '/images/screenshots/settings.png',
    demoPoster: '/images/screenshots/clips-page.png',
  },
} as const

export type SiteConfig = typeof SITE
